### ISSUE TITLE
Soundscape Editor - Unable to Change Pitch, causes infinite zeros to generate.

### ISSUE THREAD

**Issue by Dschartt** [jean-knapp/xblah-modding-tool#57]
When attempting to change the pitch of a sound file in the soundscape editor, the editor will either force the value to default to a zero or continue to add a zero to the value whenever you click in the window. 

and no, zero is not the default for the sound files, using zero causes none of the files to play because they've been slowed down to the point of inaudibility, the default is 100.

**Comment by jean-knapp** [comment]
Check in version 1.12 if this has been fixed.
