### ISSUE TITLE
Hammer++ GameConfig gets overwritten by the Modding Tool on every startup

### ISSUE THREAD

**Issue by Originope** [jean-knapp/xblah-modding-tool#60]
Hammer++'s GameConfig.txt file gets overwritten every time the Modding Tool is started. I'd like to suggest maybe checking to see if the GameConfig file is already there, and not doing anything if it is?

**Comment by Originope** [comment]
The problem it causes is that when the GameConfig file is overwritten, it erases any and all changes that have been made to it after it was created or last overwritten, E.G. the default directory to save VMF files in and the materials exclusion list - both of which are convenient to have filled in, but are cleared whenever the Modding Tool is run.

**Comment by jean-knapp** [comment]
f81352e349f30944fa0b514d5c816b7a0b1ae234

**Comment by Originope** [comment]
I think these would be a good few directories to have in the exclusion list by default:
`console
debug
models
perftest
shadertest
vgui`
That should help clean up the material browser a bit, and have it only show materials that mappers would actually want to use in their maps.

**Comment by Originope** [comment]
Something I just remembered that might need adding: Hammer++ specifically uses `bin/hammerplusplus/hammerplusplus_gameconfig.txt`, not `bin/GameConfig.txt`.

**Comment by Originope** [comment]
Ah, alright then. Here's one, you'll find the list at the bottom under SourceTest.
[GameConfig.txt](https://github.com/jean-knapp/xblah-modding-tool/files/8019838/GameConfig.txt)

**Comment by jean-knapp** [comment]
Done. Added an exclusion list. 
![image](https://user-images.githubusercontent.com/81480122/153040415-0820a453-1151-4bc2-ab66-abe5f192339d.png)
