### ISSUE TITLE
Cannot change mod installation path

### ISSUE THREAD

**Issue by TheGlassEmperor** [jean-knapp/xblah-modding-tool#66]
I don't know if it's just me, but I cannot change where mods are installed or made. It only lets me put them in  C:/, so I have to manually put them in another drive.
![image](https://user-images.githubusercontent.com/92340243/173208187-3f3f6d8b-32c2-49b6-bd7e-3252549c7a77.png)

**Comment by C-Husky** [comment]
yea same for me

**Comment by HazardousGen** [comment]
Steam Library's i think 
![image](https://user-images.githubusercontent.com/94206990/189549179-4be0c710-50ba-4372-86c2-6730c244ee71.png)

**Comment by jean-knapp** [comment]
This is a steam thing. Source mods go under your sourcemods dir, which is under steam dir.
