### ISSUE TITLE
Hud breaks after saving in the Hud editor after changing something.

### ISSUE THREAD

**Issue by ethen-short** [jean-knapp/xblah-modding-tool#69]
Recently I wanted to use the Hud editor that was in the tool. I wanted to do a simple color change and nothing more or less. After I changed it and saved. I ran the mod only to find the title screen Ui to have been cramped into the top right corner. Once I entered a map the entire Hud was missing and I saw a small pink square on the top right of the screen. unable to see health, armor, suit power for breathing underwater, sprinting or using flashlight, weapon select is also invisible. I hope this gets fixed in the near future

**Comment by jean-knapp** [comment]
HUD Editor is deprecated. It was too much work to render a preview and I stopped working on it. Sorry for the trouble.
