### ISSUE TITLE
Not launching.

### ISSUE THREAD

**Issue by IviorDum** [jean-knapp/xblah-modding-tool#70]
When i try to launch my mod from the editor. IT doesn't launch it. And gives me this:
![error1](https://user-images.githubusercontent.com/110790302/183312033-5d59bbe5-c2ca-487b-91c8-5ec109c41326.png).
EVEN if i'm already logged in on steam.
And when i reload. It gives me this:
![error2](https://user-images.githubusercontent.com/110790302/183312065-d415dcd2-4d51-4c94-a2ba-c9b22d4fbfcc.png)

So what is this.

**Comment by jean-knapp** [comment]
Fixed in v1.13.0 for new mods.
