### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by h57758** [jean-knapp/xblah-modding-tool#72]
I think this might be a virus. 
https://www.virustotal.com/gui/file/f477f5a55563eedfb177d7b68bab8e62f4a23bc547518a7e663a334e35c24395

**Comment by h57758** [comment]
Could be nice if someone looked through the code. It won't be me though.

**Comment by C-Husky** [comment]
https://www.virustotal.com/gui/file/eabc70496c5b0390ca9218a835d2fa68be380d8d777443b7af70eaadd988f8f5 its not

**Comment by h57758** [comment]
Check the "Relations" tab on VirusTotal.

**Comment by h57758** [comment]
> https://www.virustotal.com/gui/file/eabc70496c5b0390ca9218a835d2fa68be380d8d777443b7af70eaadd988f8f5 its not

It is look at the relations tab: https://www.virustotal.com/gui/file/eabc70496c5b0390ca9218a835d2fa68be380d8d777443b7af70eaadd988f8f5/relations

**Comment by TheAwesome98-Real** [comment]
obviously not

**Comment by h57758** [comment]
> obviously not

You should be more careful about what you are saying, 25 detections smell fishy.

**Comment by TheAwesome98-Real** [comment]
> > obviously not
> 
> You should be more careful about what you are saying, 25 detections smell fishy.

me when me when
![image](https://user-images.githubusercontent.com/59254971/189489158-ceeddcae-b219-4f1b-8eda-f26d7725968e.png)

**Comment by h57758** [comment]
> > > obviously not
> > 
> > 
> > You should be more careful about what you are saying, 25 detections smell fishy.
> 
> me when me when ![image](https://user-images.githubusercontent.com/59254971/189489158-ceeddcae-b219-4f1b-8eda-f26d7725968e.png)

Huh, that’s strange, when I first scanned it there were plenty of detections. 25 detections when I first scanned.

**Comment by h57758** [comment]
I think I will try this software out now!

**Comment by h57758** [comment]
But I will do it within a sandbox

**Comment by TheAwesome98-Real** [comment]
> > > > obviously not
> > > 
> > > 
> > > You should be more careful about what you are saying, 25 detections smell fishy.
> > 
> > 
> > me when me when ![image](https://user-images.githubusercontent.com/59254971/189489158-ceeddcae-b219-4f1b-8eda-f26d7725968e.png)
> 
> Huh, that’s strange, when I first scanned it there were plenty of detections. 25 detections when I first scanned.

malware-scanning engines get better (i.e. no more false positives)

**Comment by h57758** [comment]
> > > > > obviously not
> > > > 
> > > > 
> > > > You should be more careful about what you are saying, 25 detections smell fishy.
> > > 
> > > 
> > > me when me when ![image](https://user-images.githubusercontent.com/59254971/189489158-ceeddcae-b219-4f1b-8eda-f26d7725968e.png)
> > 
> > 
> > Huh, that’s strange, when I first scanned it there were plenty of detections. 25 detections when I first scanned.
> 
> malware-scanning engines get better (i.e. no more false positives)

Yeah, I know.

**Comment by jean-knapp** [comment]
vbsp gets triggered by some antivirus, but the team who makes it is trustable. The vbsp is from Mapbase. I understand your concern. The latest mapbase version solved this issue, but it`s still in beta, so I didn`t include it in the tool.
