### ISSUE TITLE
The given key was not present in the dictionary, Could not load library content.

### ISSUE THREAD

**Issue by ReplayDEVYT** [jean-knapp/xblah-modding-tool#73]
Hello. I was planning on making a Half-Life 2 mod and tried using mapbase, but it just gave me an error message that read, "The given key was not present in the dictionary." Whenever I try to launch the mod (SP2013) it immediately closes and says "Could not load library content."

**Full error logs:**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at xblah_modding_tool.MainForm.menuFile_ItemClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.12.0.0
    Win32 Version: 1.12.0.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/XBLAH's%20Modding%20Tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.Utils.v20.2.DLL
----------------------------------------
DevExpress.Data.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.Data.v20.2.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Data.Desktop.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.Data.Desktop.v20.2.DLL
----------------------------------------
DevExpress.XtraBars.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.XtraBars.v20.2.DLL
----------------------------------------
DevExpress.XtraEditors.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.XtraEditors.v20.2.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
xblah-modding-lib
    Assembly Version: 1.12.0.0
    Win32 Version: 1.12.0.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/xblah-modding-lib.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
DevExpress.XtraLayout.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/Libs/DevExpress.XtraLayout.v20.2.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.12.0.0
    Win32 Version: 1.12.0.0
    CodeBase: file:///C:/Users/bowmy/Documents/ModdingTool/XBLAH's%20Modding%20Tool.exe
----------------------------------------`

Any help would be appreciated. Thanks!
![image](https://user-images.githubusercontent.com/91987199/189504085-510e8e50-1186-4c55-b266-d1dfcb6f4721.png)
![image](https://user-images.githubusercontent.com/91987199/189504089-d699120f-1054-44a8-bb6e-e5bd338db843.png)

**Comment by rgamesonline** [comment]
i've been having an issue just like this as well, hoping this can get patched soon

**Comment by HazardousGen** [comment]
1. Open up steamapps\<user>\source sdk base\source test\bin (If you dont have this directory use [GCFScape](http://nemesis.thewavelength.net/) to find it in source sdk base.gcf

2. Grab the client.dll and server.dll files from there

3. put them in steamapps\sourcemods\<mymod>\bin

And there you have it!

took this from here
https://www.interlopers.net/forum/viewtopic.php?t=16002#wrap

**Comment by ReplayDEVYT** [comment]
Thanks! Im on a different computer so ill try it on here too, and see if it works.

> 1. Open up steamapps<user>\source sdk base\source test\bin (If you dont have this directory use [GCFScape](http://nemesis.thewavelength.net/) to find it in source sdk base.gcf
> 2. Grab the client.dll and server.dll files from there
> 3. put them in steamapps\sourcemods<mymod>\bin
> 
> And there you have it!
> 
> took this from here https://www.interlopers.net/forum/viewtopic.php?t=16002#wrap

**Comment by jean-knapp** [comment]
Fixed in v1.13.0 for new mods.
