### ISSUE TITLE
How to Fix "Could Not Load Library Client"

### ISSUE THREAD

**Issue by HazardousGen** [jean-knapp/xblah-modding-tool#74]
**Its annoying but a simple fix:

1. Open up steamapps\<user>\source sdk base\source test\bin (If you dont have this directory use [GCFScape](http://nemesis.thewavelength.net/) to find it in source sdk base.gcf

2. Grab the client.dll and server.dll files from there

3. put them in steamapps\sourcemods\<mymod>\bin

And there you have it!**

Credits to [Mr. Happy](https://www.interlopers.net/forum/memberlist.php?mode=viewprofile&u=4099&sid=8079628c8c17cab33ec31c3f9e539351)

Taken From:
https://www.interlopers.net/forum/viewtopic.php?t=16002#wrap

**Comment by HazardousGen** [comment]
Hope this helps newcomers

**Comment by jean-knapp** [comment]
Fixed in v1.13.0 for new mods.
